name: gitop-argocd-clean-project

on:
  push: 
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Build Docker image
      run: |
        docker build -t ssm0712/gitops-argocd-clean-project:${{ github.sha }} .
        docker build -t ssm0712/gitops-argocd-clean-project:latest .

    - name: Docker hub login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push images to dockerhub
      run: |
        docker push ssm0712/gitops-argocd-clean-project:${{ github.sha }}
        docker push ssm0712/gitops-argocd-clean-project:latest

    - name: Update deployment 
      run: |
        git config user.name "github-actions"   
        git config user.email "github@gmail.com"
        
        sed -i "s|image: .*|image: ssm0712/gitops-argocd-clean-project:${{ github.sha }}|" kubernetes/deployment.yaml
        git add kubernetes/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}" | echo "No changes"
        git push origin main
